/*
  a
b   f
  g
c   e
  d   p
*/


#define LCD7_SEGMENTO_E     0b01000000
#define LCD7_SEGMENTO_D     0b00100000
#define LCD7_SEGMENTO_C     0b00010000
#define LCD7_SEGMENTO_F     0b00001000
#define LCD7_SEGMENTO_A     0b00000100 
#define LCD7_SEGMENTO_B     0b00000010
#define LCD7_SEGMENTO_G     0b00000001
#define LCD7_SEGMENTO_PUNTO 0b10000000

#define LCD7_DIGITO_0 (LCD7_SEGMENTO_A + LCD7_SEGMENTO_F + LCD7_SEGMENTO_E + LCD7_SEGMENTO_D + LCD7_SEGMENTO_C + LCD7_SEGMENTO_B)
#define LCD7_DIGITO_1 (LCD7_SEGMENTO_F + LCD7_SEGMENTO_E)
#define LCD7_DIGITO_2 (LCD7_SEGMENTO_A + LCD7_SEGMENTO_F + LCD7_SEGMENTO_G + LCD7_SEGMENTO_C + LCD7_SEGMENTO_D)
#define LCD7_DIGITO_3 (LCD7_SEGMENTO_A + LCD7_SEGMENTO_F + LCD7_SEGMENTO_G + LCD7_SEGMENTO_E + LCD7_SEGMENTO_D)
#define LCD7_DIGITO_4 (LCD7_SEGMENTO_B + LCD7_SEGMENTO_G + LCD7_SEGMENTO_F + LCD7_SEGMENTO_E)
#define LCD7_DIGITO_5 (LCD7_SEGMENTO_A + LCD7_SEGMENTO_B + LCD7_SEGMENTO_G + LCD7_SEGMENTO_E + LCD7_SEGMENTO_D)
#define LCD7_DIGITO_6 (LCD7_SEGMENTO_A + LCD7_SEGMENTO_B + LCD7_SEGMENTO_G + LCD7_SEGMENTO_E + LCD7_SEGMENTO_D + LCD7_SEGMENTO_C)
#define LCD7_DIGITO_7 (LCD7_SEGMENTO_A + LCD7_SEGMENTO_F + LCD7_SEGMENTO_E)
#define LCD7_DIGITO_8 (LCD7_SEGMENTO_A + LCD7_SEGMENTO_B + LCD7_SEGMENTO_C + LCD7_SEGMENTO_D + LCD7_SEGMENTO_E + LCD7_SEGMENTO_F + LCD7_SEGMENTO_G)
#define LCD7_DIGITO_9 (LCD7_SEGMENTO_A + LCD7_SEGMENTO_B + LCD7_SEGMENTO_D + LCD7_SEGMENTO_E + LCD7_SEGMENTO_F + LCD7_SEGMENTO_G)

#define LCD7_DIGITO_NULL 0b00000000
#define LCD7_DIGITO_MENOS LCD7_SEGMENTO_G
#define LCD7_DIGITO_EXCESO LCD7_SEGMENTO_B + LCD7_SEGMENTO_C + LCD7_SEGMENTO_G + LCD7_SEGMENTO_F + LCD7_SEGMENTO_E
#define LCD7_DIGITO_DECESO LCD7_SEGMENTO_B + LCD7_SEGMENTO_C + LCD7_SEGMENTO_D
#define LCD7_DIGITO_ERROR LCD7_SEGMENTO_A + LCD7_SEGMENTO_B + LCD7_SEGMENTO_G + LCD7_SEGMENTO_C + LCD7_SEGMENTO_D
#define LCD7_DIGITO_A LCD7_SEGMENTO_A + LCD7_SEGMENTO_B + LCD7_SEGMENTO_C + LCD7_SEGMENTO_E + LCD7_SEGMENTO_F + LCD7_SEGMENTO_G

byte const pantalla_bits_vcc_array_nums[10] = {LCD7_DIGITO_0,LCD7_DIGITO_1,LCD7_DIGITO_2,LCD7_DIGITO_3,LCD7_DIGITO_4,LCD7_DIGITO_5,LCD7_DIGITO_6,LCD7_DIGITO_7,LCD7_DIGITO_8,LCD7_DIGITO_9};
char Lcd7_digito[5] = "0.00";

class Lcd7
{
    private:
        static byte get_lcd_char(char);
        static byte brillo_get_value(byte percent);

    public:
        static bool disponible();
        static void actualiza_pin();
        static void refresca_pantallas();
        static void demo();
        static void test();
        static void set_digito(float set_digito);
        static void set_digito_error();
        static void set_digito_null();
        static void set_digito_desactivado();
};
