#define	DISPOSITIVO_DE_SALIDA_BOMBA_1                   200
#define	DISPOSITIVO_DE_SALIDA_BOMBA_2                   201
#define	DISPOSITIVO_DE_SALIDA_BOMBA_3                   202
#define	DISPOSITIVO_DE_SALIDA_BOMBA_PULSADA_1           203
#define	DISPOSITIVO_DE_SALIDA_BOMBA_PULSADA_2           204
#define	DISPOSITIVO_DE_SALIDA_BOMBA_PULSADA_3           205
#define	DISPOSITIVO_DE_SALIDA_CALENTADOR                206
#define	DISPOSITIVO_DE_SALIDA_REFRIGERADOR_1            207
#define	DISPOSITIVO_DE_SALIDA_REFRIGERADOR_2            208
#define	DISPOSITIVO_DE_SALIDA_REFRIGERADOR_3            209
#define	DISPOSITIVO_DE_SALIDA_AGUA			210

#define TOTAL_DISPOSITIVOS_DE_SALIDA 11