#define	DISPOSITIVO_DE_SALIDA_BOMBA_1                   200
#define	DISPOSITIVO_DE_SALIDA_BOMBA_PULSADA_1           201
#define	DISPOSITIVO_DE_SALIDA_CALENTADOR                202
#define	DISPOSITIVO_DE_SALIDA_REFRIGERADOR_1            203

#define TOTAL_DISPOSITIVOS_DE_SALIDA 4