#define	DISPOSITIVO_DE_ENTRADA_NULL			100
#define	DISPOSITIVO_DE_ENTRADA_DEPOSITO			101
#define	DISPOSITIVO_DE_ENTRADA_ZTERMOSTATO		102 
#define	DISPOSITIVO_DE_ENTRADA_COLECTOR_1		103
#define	DISPOSITIVO_DE_ENTRADA_BOMBA_ALGORITMO          104

#define TOTAL_DISPOSITIVOS_DE_ENTRADA 5